- hosts: terraform-ansible
  tasks:
  - name: Instalando Python]
    apt:
      pkg: 
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando dependencias com pip (Django e Django Rest)
    pip:
     virtualenv: /home/ubuntu/tcc/venv
     name:
     - django
     - djangorestframework
